# Project: SVM Enroll Demo Host (Win32)
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = obj/driver.o obj/serial_win.o
LINKOBJ  = obj/driver.o obj/serial_win.o
LIBS     = -L"C:/Dev-Cpp/MinGW32/lib" -L"C:/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -s
INCS     = -I"C:/Dev-Cpp/MinGW32/include" -I"C:/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW32/include" -I"C:/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = bin/svm_enroll_win32.exe
CXXFLAGS = $(CXXINCS) -ansi -std=c99 -Wall
CFLAGS   = $(INCS) -ansi -std=c99 -Wall
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

obj/driver.o: src/driver.c
	$(CC) -c src/driver.c -o obj/driver.o $(CFLAGS)

obj/serial_win.o: src/serial_win.c
	$(CC) -c src/serial_win.c -o obj/serial_win.o $(CFLAGS)
